fix &backupskip splitting
zhimsel/vim-stay pull request #33
Opened 2016-10-04 14:31 UTC by Konfekt

Before, the delimiter would swallow the character before the separator ','

2016-10-04 15:19 UTC, kopischke requested changes
Excellent catch (don’t know how I missed that). However, te solution would be to make the `[^\\]` part a negative lookback (using `\zs` if that works in `split()`. The regex your PR introduces would split on escaped commas that are part of the path. 

Also, I am curious why you feel you have to strip spaces? Is spacing commas a valid way to separate option lists? In that case, you would still have to make sure escaped trailing spaces are not skipped…

2016-10-04 16:16 UTC, kopischke commented
Egad, GitHub PR Review mode won’t let you edit comments.

2016-10-04 20:31 UTC, Konfekt commented
Fine with your corrections. The need to strip spaces comes from Vim considering
`/var/tmp/*  ,    /tmp/*` and `/var/tmp/*, /tmp/*` equal as &backupskip values. 

Injecting superfluous spaces before `,` is how I work around the current splitting bug.

2016-10-04 20:32 UTC, Konfekt commented
I think you missed it because the default value is `/tmp/*,/tmp/*` on Linux. Thus one `/tmp/*`, the last one, survives.

2018-06-01 20:58 UTC, Konfekt commented
Well, I am not sure I understood @kopischke 's comments. Is
```vim
\m[^\\]\%(\\\\\)*\s*,\s*')
```
the way to go?

2018-06-01 21:29 UTC, kopischke commented
Well, actually (\*keeps,on writing through the uproar of mute filters), this is fixed in the 1.4 branch by commit 594443fa0cf9b850c63931aea9d0951a52f1a324.

2018-07-18 13:22 UTC, Konfekt commented
@zhimsel It seem that the 1.4 branch stood the test of time. Perhaps it could be released soon?

2018-07-18 18:47 UTC, zhimsel commented
@Konfekt I've been thinking the same thing. Sorry about all the maintenance delays. Both Martin and I have been super busy :(

I'll look through the `release/1.4` branch very soon and merge it.

2018-07-18 18:49 UTC, zhimsel commented
@Konfekt can you confirm that the `release/1.4.0` branch has fixed this issue? Martin above said that it was fixed separately. If so, we can close this PR once 1.4.0 has been released.

2018-07-19 12:59 UTC, Konfekt commented
Yes, works fine!

2018-07-19 20:59 UTC, zhimsel commented
Awesome, thanks! Closing this issue.

2018-07-19 20:59 UTC, closed without merging